//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Personal_App.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("lame.exe")]
        public string LameExePath {
            get {
                return ((string)(this["LameExePath"]));
            }
            set {
                this["LameExePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://static.365speak.cn/update/xyybs1/update_xyybs.xml")]
        public string UpdateUrl111 {
            get {
                return ((string)(this["UpdateUrl111"]));
            }
            set {
                this["UpdateUrl111"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("您现在还没有新作业~")]
        public string NoHomework {
            get {
                return ((string)(this["NoHomework"]));
            }
            set {
                this["NoHomework"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("您现在还没有完成的作业~")]
        public string NoOverHomework {
            get {
                return ((string)(this["NoOverHomework"]));
            }
            set {
                this["NoOverHomework"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("该手机号已注册，请直接登录！")]
        public string UsedPhoneNum {
            get {
                return ((string)(this["UsedPhoneNum"]));
            }
            set {
                this["UsedPhoneNum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("请输入有效的16位学习卡号~")]
        public string ErrorCardNum {
            get {
                return ((string)(this["ErrorCardNum"]));
            }
            set {
                this["ErrorCardNum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://static.365speak.cn/update/xyybs/{0}")]
        public string UpdateUrl {
            get {
                return ((string)(this["UpdateUrl"]));
            }
            set {
                this["UpdateUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("update_xyybs.xml")]
        public string UpdateFileName {
            get {
                return ((string)(this["UpdateFileName"]));
            }
            set {
                this["UpdateFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("网络连接超时，下载失败")]
        public string PaperDownloadTimeOut {
            get {
                return ((string)(this["PaperDownloadTimeOut"]));
            }
            set {
                this["PaperDownloadTimeOut"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("你的网络开小差了，请检查网络设置后重新下载！")]
        public string PaperDownloadTimeOut1 {
            get {
                return ((string)(this["PaperDownloadTimeOut1"]));
            }
            set {
                this["PaperDownloadTimeOut1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("莫急~ 内容正在路上，还有几站地就到 ~")]
        public string NoExamPaper {
            get {
                return ((string)(this["NoExamPaper"]));
            }
            set {
                this["NoExamPaper"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("莫急~ 内容正在路上，还有几站地就到 ~")]
        public string NoTrainPaper {
            get {
                return ((string)(this["NoTrainPaper"]));
            }
            set {
                this["NoTrainPaper"] = value;
            }
        }
    }
}
